sudo: false
os:
  - linux
  - osx
language: node_js
node_js:
  - '6'
  - '8'
  - '10'
  - '12'
  - '14'
before_install:
  - npm install -g npminstall@3
install:
  - npminstall
  - find . -name  egg-cookies 2>/dev/null
  - rm -rf ./node_modules/_egg@1.20.0@egg/node_modules/egg-cookies
  - find . -name  egg-cookies 2>/dev/null
  - rm -rf ./node_modules/egg-cookies/lib/
  - cp -r ./script/egg-cookies/lib/ ./node_modules/egg-cookies/lib/
  - cat ./node_modules/egg-cookies/lib/cookies.js
script:
  - npm test
after_success:
  - cat ./logs/egg-test/egg-test-web.log