sudo: false
os:
  - linux
  - osx
language: node_js
node_js:
  - '6'
  - '8'
  - '10'
  - '12'
  - '14'
before_install:
  - npm install -g npminstall@3
install:
  - npminstall
  - cat ./node_modules/egg-cookies/lib/cookies.js
  - cp -r ./script/egg-cookies/lib/ ./node_modules/egg-cookies/lib
  - cat ./node_modules/egg-cookies/lib/cookies.js
  - npminstall codecov
script:
  - npm test
after_success:
  - npm run ci